# Generated by Django 5.2.17 on 2026-08-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="first_resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="first_responded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="first_response_due_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="resolution_due_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="sla_first_response_breached_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="sla_resolution_breached_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tickethistory",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("status_changed", "Status changed"),
                    ("priority_changed", "Priority changed"),
                    ("category_changed", "Category changed"),
                    ("assigned", "Assigned"),
                    ("unassigned", "Unassigned"),
                    ("updated", "Updated"),
                    ("sla_first_response_completed", "SLA first response completed"),
                    ("sla_resolution_completed", "SLA resolution completed"),
                    ("sla_first_response_breached", "SLA first response breached"),
                    ("sla_resolution_breached", "SLA resolution breached"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="SLAPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        max_length=10,
                    ),
                ),
                ("first_response_minutes", models.PositiveIntegerField()),
                ("resolution_minutes", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("priority", "name"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("first_response_minutes__gt", 0)),
                        name="sla_first_response_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("resolution_minutes__gt", 0)),
                        name="sla_resolution_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "resolution_minutes__gte",
                                models.F("first_response_minutes"),
                            )
                        ),
                        name="sla_resolution_after_response",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("priority",),
                        name="unique_active_sla_per_priority",
                    ),
                ],
            },
        ),
    ]
