# Generated by Django 5.2.17 on 2026-08-27 19:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_ticket_first_resolved_at_ticket_first_responded_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="tickethistory",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("status_changed", "Status changed"),
                    ("priority_changed", "Priority changed"),
                    ("category_changed", "Category changed"),
                    ("assigned", "Assigned"),
                    ("unassigned", "Unassigned"),
                    ("updated", "Updated"),
                    ("sla_first_response_completed", "SLA first response completed"),
                    ("sla_resolution_completed", "SLA resolution completed"),
                    ("sla_first_response_breached", "SLA first response breached"),
                    ("sla_resolution_breached", "SLA resolution breached"),
                    ("attachment_uploaded", "Attachment uploaded"),
                    ("attachment_deleted", "Attachment deleted"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="TicketAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("storage_key", models.CharField(max_length=255, unique=True)),
                ("content_type", models.CharField(max_length=150)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="tickets.ticket",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ticket_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
