# Generated by Django 5.2.17 on 2026-08-27 19:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_alter_tickethistory_action_ticketattachment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["status", "-created_at"], name="ticket_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["priority", "-created_at"], name="ticket_priority_created_idx"
            ),
        ),
    ]
